labels:
  'approved': 
    action: merge
  'hacktoberfest-accepted':
    action: merge


commits:
  - action: label
    pattern: /Create/i
    labels:
      - good first issue
      - hacktoberfest-accepted
  
